### ISSUE TITLE
Lithe stuff out of Berkeley

### ISSUE THREAD

**Issue by npe9** [hq6/Thesis_Proposal#1]
You might want to cite the Lithe stuff out of Berkeley. They use a similar approach to yours (although notably no kernel support) to multiplex multiple runtimes to particular cores.

http://lithe.eecs.berkeley.edu/

**Comment by hq6** [comment]
I have already looked at this one. This version of my proposal is slightly out of date since I decided to move to Google Slides for the version after this. Thanks!

**Comment by npe9** [comment]
No problem at all. Happy to help :)
